package com.examplecom.springbootsample.demo.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@Entity
@Table(name="EMPLOYEE_DETAILS")
@ApiModel(description = "All details about the Employee. ")
//@NamedQuery(name="Employee.findByLocation", query= "SELECT u FROM Employee u where u.location<= ?1")
public class Employee implements Serializable{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@ApiModelProperty(value="Employee ID generated by database")
	private long id;
	
	@Column(name="EMP_NAME")
	@ApiModelProperty(value="Employee Name")
	private String employeeName;
	
	@Column(name="DEPT")
	@ApiModelProperty(value="Department Employee works in")
	private String department;
	
	@Column(name="LOCATION")
	@ApiModelProperty(value="Location defines the distance from office to Employee home")
	private int location;
	
	
	public void empl() {
		
	}
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getEmployeeName() {
		return employeeName;
	}
	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}
	public int getLocation() {
		return location;
	}
	public void setLocation(int location) {
		this.location = location;
	}
	
	
	
	
	
	
}
